### ISSUE TITLE
Command line option?

### ISSUE THREAD

**Issue by zach-morris** [Sappharad/MultiPatch#11]
I very much like this tool, so thanks for making it.
Question command line usage.  Is it available?  For lots of files on a mac, command line automation would be preferred

**Comment by Sappharad** [comment]
Yes, it’s on the website

**Comment by zach-morris** [comment]
OK.  Where exactly?  I've read the readme, and looked on your site, but there is no mention that I can find for command line options.

**Comment by Sappharad** [comment]
It’s the 5th question in the FAQ
https://projects.sappharad.com/mp3gain/

**Comment by zach-morris** [comment]
I think you're looking at a different project.  This is MultiPatch
http://projects.sappharad.com/tools/multipatch.html

**Comment by Sappharad** [comment]
Oops. Sorry, I usually get command line requests for that. Never expected one for this.
