### ISSUE TITLE
major problem with ppf (still not working properly)

### ISSUE THREAD

**Issue by pleasejustgo** [Sappharad/MultiPatch#17]
Hi, I just tried to apply Quality hack 1.3 (https://www.romhacking.net/hacks/3606/) to Symphony of the Night (crc32 of track 1: 05be47b2) and it didn't work properly. Right from the beginning you can see on the title screen, it should read in the top right corner "Qualiy Hack 1.3", but it's thick black unreadable font. Then the "Journey back to Transylvania 1792" or whatever screen is missing, it goes straight to map and then a black screen during the prologue. The audio works and is sounds like you can play but you can't see anything. Just a line of pixels at the top, that's all.

Using ppf-o-matic on windows, it all works fine.

I should add that after applying this, just to be safe I always use ECC recalc on a PS1 disc image. Many hacks need this to be applied when making changes to a disk for the game to work properly. (https://www.romhacking.net/utilities/1264/)

**Comment by Sappharad** [comment]
Did you upgrade to 1.8? The last release literally replaced the PPF engine entirely with the same one PPF-o-matic uses.

**Comment by Sappharad** [comment]
Works for me. User is not running latest software.
