### ISSUE TITLE
Problems with UTF characters in path

### ISSUE THREAD

**Issue by Schaefers** [Sappharad/MultiPatch#18]
Having a UTF character like `é` in the patch path (probably same problems for the other paths, as well) causes the patch loading to fail.

**Comment by Sappharad** [comment]
I disagree. Please provide additional information. (And yes, the output file was correct) Are you perhaps running an outdated version of the application?
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1350664/136672193-21f1bcc7-ebb7-4c78-9c2c-32a6cf7394e9.png">

I also tried copy/pasting the letter you had above into the filename it also worked.

**Comment by Schaefers** [comment]
![image](https://user-images.githubusercontent.com/9284160/136672239-f7869615-a462-4109-be76-35b8a8142de3.png)

After renaming to just `sors.ups` it works as expected. The file was selected using the "Browse..." button. Full path in the text field is `/Users/christianschafers/Downloads/Pokémon Sors 2021 1.2 (Bug Fix Patch) Full Release (Official By Vytron)/Pokémon Sors - 2021 Full Release 1.2 (Bug Fix Patch) - By Vytron.ups`

**Comment by Sappharad** [comment]
From your photo above, that's an old version. Please try again in the current version.

**Comment by Schaefers** [comment]
You're right, I was _still_ using v1.8, updating solved the problem. Sorry for the circumstances.

**Comment by Sappharad** [comment]
Version 2.0 has a "Check for updates" feature so hopefully this will happen less in the future. You are the first one to report it, but someone else submitted the fix for that to me earlier this year as a pull request.

**Comment by Schaefers** [comment]
Great, thanks for your work!
