### ISSUE TITLE
Unable to load BPS files

### ISSUE THREAD

**Issue by OverLoadedPanda** [Sappharad/MultiPatch#5]
Hi, I'm on macOS Sierra: 10.12.3 And I am unable to patch .BPS files to my rom. I am trying to patch Super Mario Logic (a BPS file obviously) to Super Mario World (a .smc file) I am using the latest version of MultiPatch (1.6.2) The rom is definitely clean and I downloaded the Super Mario Logic.BPS file off of SMWcentral.com so it is obviously safe. I am using OpenEmu as my emulator as well. So basically what happens is, I boot up MultiPatch and select the correct files, in the correct slots and add the name and then click "Apply Patch" And I get hit with the following: 

> Pathing Failed: The source file checksum is invalid. This usually means that the file you have picked to patch is not the correct file.

 I have no idea what to do, and have searched all over the internet, to no help, so I came here. Would help if you guys could tell me what I'm doing wrong.

**Comment by Sappharad** [comment]
The error message is probably correct, the ROM is not the right one. Perhaps the site where you got the patch tells you exactly which version of the ROM you need? There are several versions of SMW.

**Comment by GB-CG** [comment]
Some romhacks may require a headed or unheaded ROM. There's a windows program called Tush where it can add or remove headers. Not sure if there's a Mac equivalent of Tush, but it works with Wine.

**Comment by GB-CG** [comment]
Can confirm, an _un_headed Super Mario World ROM with Logic BPS patch patched successfully. Whereas with an header, it does not.

**Comment by OverLoadedPanda** [comment]
Thanks for leaving the comments guys, I will try it out In a couple hours when I get back home. @GB-CG would you be able to send me a link to download an unheaded super mario world rom? I can't find one after doing a quick search :) Thanks all.

**Comment by GB-CG** [comment]
Well, you already have the rom, so... :)

1. Google 'nsrt mac' (1st result should be a romhacking(.)net link)
2. Once you have .gz file, extract it,
3. Open the .dmg file, quick look at 'read me first!.txt'
4. Make a new folder, drag the 'nf.app' and the ROM in to it
5. Open the app, select 'Browse' and choose that folder with your ROM in, it should show up on the left side of the app,
6. Left click it, then choose 'Remove headers from selected', rescan.
7. Your ROM is now unheaded!

If that somehow doesn't work, google 'snes tush'.

**Comment by Sappharad** [comment]
@GB-CG Thanks for providing user support for some reason. :-)

I'm going to close this issue since it's not a problem with the application. There's not really anything that can be done about game-specific problems. Perhaps the site where you got the patch could do a better job explaining the exact ROM they require to patch, if they don't do that already.

Unless you've got some suggestions as to a change that would help, I don't know anything I could do here.

**Comment by GB-CG** [comment]
@Sappharad Yeah, I've noticed early on that it's not really an MultiPatch issue, but at least we helped the person.
